force_cast: error
force_try: error
force_unwrapping:
  severity: error

opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - explicit_init
  - fatal_error_message
  - first_where
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - switch_case_on_newline
  - force_unwrapping
  - implicitly_unwrapped_optional
  
type_body_length:
  warning: 400
  error: 600
  
private_outlet:
  allow_private_set: true
  
file_length:
  warning: 600
  error: 800
  
function_body_length:
  warning: 40
  error: 60
  
implicitly_unwrapped_optional:
  mode: all
  severity: error
  
disabled_rules:
  - type_name
  - identifier_name
  - no_space_in_method_call
  
included:
  - Sources/MoviedbMVVMC

excluded:
  - Pods
  - Sources/Tests